name: CI

on:
  push:
    branches:
      - "main"

jobs:
  cdk-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS CLI
        run: |
            sudo apt-get update
            sudo apt-get install awscli
            mkdir ~/.aws/ 
            touch ~/.aws/credentials 
            touch ~/.aws/config 
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region us-east-1

      - name: Deploy CDK App
        run: npm run destroy
